name: Release
on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: "ubuntu-latest"
    strategy:
      matrix: 
        include:
          - node-version: 11.x
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: build and deploy
        run: yarn && yarn test:prod && yarn build && yarn deploy-docs
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
