name: Release
on:
  push:
    branches:
      - [ master, main ]
  pull_request:
    branches:
      - [ master, main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest,
    strategy:
      matrix: 
        include:
          - node-version: 10.x
    steps:
      - name: Checkout
      - uses: actions/checkout@master

      - name: Build and Deploy
      - uses: JamesIves/github-pages-deploy-action@master
      - env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        BUILD_SCRIPT: yarn && yarn test:prod && yarn build
